OLED_DRIVER_ENABLE = yes 	# Enables the use of OLED displays
ENCODER_ENABLE = yes		# Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes		# Enable keyboard RGB underglow
LEADER_ENABLE = yes			# Enable the Leader Key feature
MOUSEKEY_ENABLE = yes		# Enable Mouse Keys
TAP_DANCE_ENABLE = no		# Enable Tap Dance
COMBO_ENABLE = yes			# Enable Combo
AUTO_SHIFT_ENABLE = yes     # Enable Auto Shift
DYNAMIC_TAPPING_TERM_ENABLE = yes